# Implement LSH from scratch

In this assignment, you will implement LSH from scratch and predict the labels of the test data. You will then verify the correctness of the your implementation using a "grader" function/cell (provided by us) which will match your implmentation.

The grader fucntion would help you validate the correctness of your code. 

Please submit the final Colab notebook in the classroom ONLY after you have verified your code using the grader function/cell.


**NOTE: DO NOT change the "grader" functions or code snippets written by us.Please add your code in the suggested locations.**

Ethics Code:
1. You are welcome to read up online resources to implement the code. 
2. You can also discuss with your classmates on the implmentation over Slack.
3. But, the code you wirte and submit should be yours ONLY. Your code will be compared against other stduents' code and online code snippets to check for plagiarism. If your code is found to be plagiarised, you will be awarded zero-marks for all assignments, which have a 10% wieghtage in the final marks for this course.

## Reading the data from csv file

In [1]:
# Code to mount google drive in case you are loading the data from your google drive
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [2]:
# Loading data from csv file
import pandas as pd
data_path = '/gdrive/MyDrive/PGD Assignment Notebooks/lsh_assignment_data.csv'

df = pd.read_csv(data_path)
df

category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
2220            NaN  cars pull down us retail figures us retail sal...
2221            NaN  kilroy unveils immigration policy ex-chatshow ...
2222            NaN  rem announce new glasgow concert us band rem h...
2223            NaN  how political squabbles snowball it s become c...
2224            NaN  souness delight at euro progress boss graeme s...

[2225 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
import nltk
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
# Data Overiview
df['category'].value_counts()

sport            509
business         508
politics         415
tech             399
entertainment    384
Name: category, dtype: int64

### Creating Train and Test Datasets

Note that the labels for test data will not be present in the dataset and hence they are mentioned as NaN.

In [3]:
# The last 10 rows in the csv file are query points, so loading them into test data.
# And loading the reamining points to train_data for which labels are given.

train_data = df.iloc[:-10,:]
test_data = df.iloc[-10:,:]

In [5]:
# For train_data here the labels are in the column named "category".
train_data

category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
2210       politics  teens  know little  of politics teenagers ques...
2211  entertainment  lopez misses uk charity premiere jennifer lope...
2212       business  christmas shoppers flock to tills shops all ov...
2213           tech  progress on new internet domains by early 2005...
2214       business  bush budget seeks deep cutbacks president bush...

[2215 rows x 2 columns]

In [6]:
test_data

category                                               text
2215      NaN  junk e-mails on relentless rise spam traffic i...
2216      NaN  top stars join us tsunami tv show brad pitt  r...
2217      NaN  rings of steel combat net attacks gambling is ...
2218      NaN  davies favours gloucester future wales hooker ...
2219      NaN  beijingers fume over parking fees choking traf...
2220      NaN  cars pull down us retail figures us retail sal...
2221      NaN  kilroy unveils immigration policy ex-chatshow ...
2222      NaN  rem announce new glasgow concert us band rem h...
2223      NaN  how political squabbles snowball it s become c...
2224      NaN  souness delight at euro progress boss graeme s...

## Custom Implementation

### Instructions:

  1. Read in the train_data.
  2. Vectorize train_data using sklearns built in tfidf vectorizer.
  3. Ignore unigrams and make use of both **bigrams & trigrams** and also limit the **max features** to **4000** and **minimum document frequency** to **10**.
  4. After the tfidf vectors are generated as mentioned above, next task is to generate random hyperplanes.
  5. Generate **5 random hyperplanes**. And generate the hyperplanes using a random normal distribution with **mean zero and variance 1**. 
  6. We have set the **numpy random seed to zero**, please do not change it. And then you can make use of **np.random.normal** to generate the vectors for hyperplanes.
  7. As mentioned in the course videos, compute the hash function and also the corresponding hash table for it.
  8. Once the hash table is generated now take in each of the query points from the test data.
  9. Vectorize those query points using the same tfidf vectorizer as mentioned above.
  10. Now use the hash function on this query point and fetch all the similar data points from the hashtable.
  11. Use cosine similarity to compute **11-Nearest Neighbours** from the list of data points obtained in the above step.
  12. Take a majority vote among the 11-Nearest Neighbours and predict the class label for the query point in the test data.
  13. **In case of a tie** in the obtained labels from nearest neighbours, you can pick a label after sorting all the labels **alphabetically**(A-Z), i.e. for example labels starting with A would get more preference than labels starting with Z.
  14. Repeat steps 9 to 13 for all the points in the test data and then finally return a list with all the predicted labels.
  15. Note that there are a total of 10 data points in the test data so the final list you return should be of length 10.
  16. Also note that the cosine similarity function should be written from scratch, you should not directly make use of existing libraries.
  17. Please use the formula of cosine similarity as explained in the course videos, you can make use of numpy or scipy to calculate dot or norm or transpose.

In [84]:
# Please implement this fucntion and write your code wherever asked. Do NOT change the code snippets provided by us.

import numpy as np

def predictLabels (test_data):
  """
  Given the test_data, return the labels for all the rows in the test data.
  Follow the step by step instructions mentioned above.
  """
  import numpy as np
  np.random.seed(0)

  ##############################################################
  ####  Write YOUR CODE BELOW  as per the above instructions ###
  ##############################################################
  #Creating Tain Test data of small size
  train_data = df.iloc[:-10,:]
  test_data = df.iloc[-10:,:]
  # train_data = df.iloc[:10,:]
  # test_data = df.iloc[-10:,:]

  #Impoerting Library
  import pandas as pd
  
  import nltk
  import string
  import matplotlib.pyplot as plt
  import seaborn as sns
  from sklearn.feature_extraction.text import TfidfTransformer
  from sklearn.feature_extraction.text import TfidfVectorizer
  ######################################################################################
  #Training the TFIDF vector
  tfidf_vect=TfidfVectorizer(ngram_range=(2,3),max_features=4000,min_df=10)
  train_tfidf=tfidf_vect.fit_transform(train_data['text'].values)
  # print(train_tfidf.toarray().shape)
  # print(train_tfidf.toarray())
  Train_processed=train_tfidf.toarray()
  # pd.DataFrame(train_tfidf.toarray(),columns = tfidf_vect.get_feature_names())
  # print(Train_processed)

  ######################################################################################
  #Generate 5 random hyperplanes
  Hyperplanes=[]
  np.random.seed(0)
  for i in range(5):
    Hyperplanes.append(np.random.normal(0,1,4000))

  # print("Length of Hyper plane =", len(Hyperplanes))
  # print("Shape of fist hyper plane=", Hyperplanes[0])

  ######################################################################################
  #Creating HashValue Function to create Hash function
  def hashvalue(vect):
    hasvalues=[]
    for i in range(len(Hyperplanes)):
      hasvalues.append((np.dot(vect,Hyperplanes[i]) > 0).astype('int'))

    return tuple(hasvalues)

  ########################################################################################
  #Creating Hash Table Function

  hash_dict={}
  idx=0 # for storing the index position instead of storing tfidf of a point which will be a sparse amtrix
  for text in Train_processed:
    hash_key=hashvalue(text)
    #Check if the key is present in the dict.
    if hash_key not in hash_dict.keys():  
      hash_dict[hash_key]=list()
    hash_dict[hash_key].append(idx)
    idx+=1
    
  #Print the key value pair
  # for pairs in hash_dict.items():
  #   print(pairs)
  ########################################################################################
  # Vectorazing my Test data
  Test_tfidf=tfidf_vect.transform(test_data['text'].values)
  Test_processed=Test_tfidf.toarray()
  print(Test_processed.shape)
  # print(Test_processed[0])

  ########################################################################################

  #Now use the hash function on this query point and fetch all the similar data points from the hashtable.
#Use cosine similarity to compute 11-Nearest Neighbours from the list of data points obtained in the above step
#Defining Cosin Similarity Function
  def CosinSim(Query_pt,neigh_vect):  
    cosin_sim=np.dot(Query_pt,neigh_vect)/(np.linalg.norm(Query_pt)*np.linalg.norm(neigh_vect))
    return cosin_sim
  KNN_11=[]
  Final_ans=[]
  for i in range(Test_processed.shape[0]):
    Query_pt=Test_processed[i] #Fetching the query point
    #looping through all query point in Test data
    test_HV=hashvalue(Test_processed[i]) #Creating Hashvalue of eacch query point
    # print(test_HV)
    # print(hash_dict[test_HV_1])
    All_CosSim=[]
    neigh_pt=hash_dict[test_HV] #fetching all the neighbouring point for the query point hash value
    for indx,pt in enumerate(neigh_pt):
      # print(indx,pt)
      neigh_vect=Train_processed[pt]# for each index value in neighbouring point we are finding correspondicg vector
      
      cosim= CosinSim(Query_pt,neigh_vect) #Finding the cosin similarity between the query point and each neighbouring point ( using loop indx)
      All_CosSim.append((pt,cosim))
    
    # print("unsorted = ",All_CosSim)
    Sorted_AllCosSim=(sorted(All_CosSim, key = lambda x: x[1],reverse=True))[:12] # KNN usin cosin sim for KNN=11
    temp=[train_data['category'][x[0]] for x in Sorted_AllCosSim ] 
    Final_ans.append(max(sorted(temp),key=temp.count))
    KNN_11.append(temp)


  return Final_ans
  

# print("KNN_11-",KNN_11)
# print("Final ans-",Final_ans)





In [8]:
#Creating Tain Test data of small size
train_data = df.iloc[:-10,:]
test_data = df.iloc[-10:,:]
# train_data = df.iloc[:10,:]
# test_data = df.iloc[-10:,:]

In [9]:
#Create TFidf vector

import pandas as pd
import numpy as np
import nltk
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer


In [32]:
#Training the TFIDF vector
tfidf_vect=TfidfVectorizer(ngram_range=(2,3),max_features=4000,min_df=10)
train_tfidf=tfidf_vect.fit_transform(train_data['text'].values)
print(train_tfidf.toarray().shape)
# print(train_tfidf.toarray())
Train_processed=train_tfidf.toarray()
# pd.DataFrame(train_tfidf.toarray(),columns = tfidf_vect.get_feature_names())
print(Train_processed)

(2215, 4000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [33]:
#Generate 5 random hyperplanes
Hyperplanes=[]
np.random.seed(0)
for i in range(5):
  Hyperplanes.append(np.random.normal(0,1,4000))

print("Length of Hyper plane =", len(Hyperplanes))
print("Shape of fist hyper plane=", Hyperplanes[0])

Length of Hyper plane = 5
Shape of fist hyper plane= [ 1.76405235  0.40015721  0.97873798 ... -0.03057244  1.57708821
 -0.8128021 ]


In [34]:
#Creating HashValue Function to create Hash function
def hashvalue(vect):
  hasvalues=[]
  for i in range(len(Hyperplanes)):
    hasvalues.append((np.dot(vect,Hyperplanes[i]) > 0).astype('int'))

  return tuple(hasvalues)




In [14]:
#TESTINGGGGGGGGGGGGGGGGGGGGG
x=Train_processed[0]
x

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
# #Creating Hash Table Function

# #Creating Empty dictionary
# hash_dict={}
# for text in Train_processed:
#   hash_key=hashvalue(text)
#   #Check if the key is present in the dict.
#   if hash_key not in hash_dict.keys():
#     # hash_dict.update({hash_key,text})
#     #Below is other way
#     hash_dict[hash_key]=[]
#   hash_dict[hash_key]=text

# print(hash_dict)

In [35]:
#Creating Hash Table Function

#Creating Empty dictionary
hash_dict={}
idx=0 # for storing the index position instead of storing tfidf of a point which will be a sparse amtrix
for text in Train_processed:
  hash_key=hashvalue(text)
  #Check if the key is present in the dict.
  if hash_key not in hash_dict.keys():  
    hash_dict[hash_key]=list()
  hash_dict[hash_key].append(idx)
  idx+=1
  
#Print the key value pair
for pairs in hash_dict.items():
  print(pairs)

((0, 1, 1, 0, 1), [0, 36, 110, 113, 139, 169, 198, 278, 295, 412, 512, 549, 565, 573, 574, 688, 696, 712, 839, 887, 977, 1021, 1071, 1185, 1227, 1243, 1266, 1273, 1381, 1383, 1433, 1463, 1495, 1500, 1503, 1526, 1550, 1584, 1814, 1849, 1864, 2032, 2040, 2051, 2131, 2137, 2151])
((1, 1, 1, 1, 1), [1, 28, 54, 74, 92, 117, 118, 135, 146, 168, 172, 205, 242, 334, 388, 449, 521, 531, 532, 533, 540, 576, 615, 616, 655, 722, 781, 892, 935, 1087, 1091, 1140, 1210, 1220, 1274, 1335, 1343, 1358, 1379, 1430, 1564, 1569, 1727, 1785, 1811, 1829, 1840, 1898, 1938, 1949, 1994, 2030, 2083, 2140, 2208])
((1, 0, 0, 0, 0), [2, 27, 32, 68, 73, 219, 230, 234, 244, 346, 399, 400, 415, 479, 496, 519, 558, 670, 687, 737, 758, 760, 773, 817, 880, 889, 922, 932, 952, 1049, 1095, 1126, 1156, 1169, 1201, 1365, 1396, 1446, 1513, 1557, 1588, 1624, 1653, 1668, 1703, 1728, 1729, 1787, 1792, 1796, 1870, 1879, 1893, 2069, 2074, 2135, 2176])
((0, 1, 0, 0, 0), [3, 18, 185, 186, 195, 314, 326, 398, 424, 571, 604, 645, 672,

In [36]:
# Vectorazing my Test data
Test_tfidf=tfidf_vect.transform(test_data['text'].values)
Test_processed=Test_tfidf.toarray()
print(Test_processed.shape)
# print(Test_processed[0])

(10, 4000)


In [63]:
Query_pt=Test_processed[1]
print(hashvalue(Query_pt))
print(hash_dict[hashvalue(Query_pt)])
print(np.linalg.norm(Query_pt))

(1, 0, 1, 1, 0)
[8, 13, 35, 42, 82, 85, 95, 108, 112, 115, 120, 132, 150, 157, 159, 166, 204, 217, 249, 308, 310, 311, 322, 338, 355, 362, 364, 411, 428, 445, 480, 489, 500, 503, 525, 551, 562, 626, 651, 682, 703, 705, 766, 810, 856, 881, 906, 916, 923, 937, 954, 955, 1025, 1042, 1059, 1125, 1141, 1142, 1170, 1191, 1195, 1202, 1230, 1242, 1256, 1289, 1322, 1340, 1374, 1387, 1393, 1418, 1454, 1527, 1562, 1577, 1607, 1619, 1636, 1669, 1672, 1705, 1720, 1744, 1759, 1771, 1788, 1856, 1863, 1894, 1906, 1907, 1940, 1947, 1953, 1955, 1965, 1970, 1995, 2009, 2036, 2066, 2086, 2092, 2104, 2144, 2156, 2187]
0.9999999999999998


In [80]:
#Now use the hash function on this query point and fetch all the similar data points from the hashtable.
#Use cosine similarity to compute 11-Nearest Neighbours from the list of data points obtained in the above step
#Defining Cosin Similarity Function
def CosinSim(Query_pt,neigh_vect):  
  cosin_sim=np.dot(Query_pt,neigh_vect)/(np.linalg.norm(Query_pt)*np.linalg.norm(neigh_vect))
  return cosin_sim
KNN_11=[]
Final_ans=[]
for i in range(Test_processed.shape[0]):
  Query_pt=Test_processed[i] #Fetching the query point
  #looping through all query point in Test data
  test_HV=hashvalue(Test_processed[i]) #Creating Hashvalue of eacch query point
  print(test_HV)
  # print(hash_dict[test_HV_1])
  All_CosSim=[]
  neigh_pt=hash_dict[test_HV] #fetching all the neighbouring point for the query point hash value
  for indx,pt in enumerate(neigh_pt):
    # print(indx,pt)
    neigh_vect=Train_processed[pt]# for each index value in neighbouring point we are finding correspondicg vector
    
    cosim= CosinSim(Query_pt,neigh_vect) #Finding the cosin similarity between the query point and each neighbouring point ( using loop indx)
    All_CosSim.append((pt,cosim))
  
  print("unsorted = ",All_CosSim)
  Sorted_AllCosSim=(sorted(All_CosSim, key = lambda x: x[1],reverse=True))[:12] # KNN usin cosin sim for KNN=11
  temp=[train_data['category'][x[0]] for x in Sorted_AllCosSim ] 
  Final_ans.append(max(sorted(temp),key=temp.count))
  KNN_11.append(temp)
  

print("KNN_11-",KNN_11)
print("Final ans-",Final_ans)
  

  
  # print("SS",Sorted_AllCosSim)
  # dict[test_data['category'][i]]==Sorted_AllCosSim
     




  
  



(0, 1, 1, 1, 0)
unsorted =  [(23, 0.005262850024749239), (96, 0.01599390819941128), (105, 0.05782779241516407), (153, 0.04144110630992941), (239, 0.10942722899280966), (243, 0.0027756456362870176), (315, 0.06702712530502797), (401, 0.09309289878365656), (405, 0.01877068848038404), (468, 0.01799543898825019), (511, 0.026017069474002695), (587, 0.03312552126383352), (680, 0.004397082213909537), (694, 0.02555396015367261), (771, 0.013861905105332075), (780, 0.026206771156323635), (809, 0.008941660463043314), (847, 0.020326803035122243), (855, 0.011208754332763957), (876, 0.03189517559205342), (963, 1.0000000000000002), (973, 0.013621753338865946), (1029, 0.004438050802230254), (1113, 0.04170304183021851), (1175, 0.028404731114840827), (1223, 0.006940354131501984), (1224, 0.011607052816599128), (1378, 0.005991956612935168), (1408, 0.04513601479561055), (1416, 0.11124613300644823), (1461, 0.00581184989763069), (1481, 0.04025358563467732), (1576, 0.015601679831581072), (1665, 0.0336502132772

In [27]:
a=['tech','tech','business', 'business','politics','sport', 'sport', 'entertainment']
max(sorted(a),key=a.count)

'tech'

In [81]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the predictLabels() is correct and the accuracy obtained is above 80%.
# Else, it will print "Failed"
###########################################
import numpy as np

# Predict the labels using the predictLabels() function
Y_custom = np.array(Final_ans)

# Reference grader array - DO NOT MODIFY IT
Y_grader = np.array(['tech', 'entertainment', 'tech', 'sport', 'business', 'business', 'politics', 'entertainment', 'politics', 'sport'])

# Calculating accuracy by comparing Y_grader and Y_custom
accuracy = np.sum(Y_grader==Y_custom) * 10

if accuracy >= 80:
  print("******** Success ********","Accuracy Achieved = ", accuracy,'%')
else:
  print("####### Failed #######","Accuracy Achieved = ", accuracy,'%')
  print("\nY_grader = \n\n", Y_grader)
  print("\n","*"*50)
  print("\nY_custom = \n\n", Y_custom)


******** Success ******** Accuracy Achieved =  90 %


## Grader Cell

Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the predictLabels() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [85]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the predictLabels() is correct and the accuracy obtained is above 80%.
# Else, it will print "Failed"
###########################################
import numpy as np

# Predict the labels using the predictLabels() function
Y_custom = np.array(predictLabels(test_data))


# Reference grader array - DO NOT MODIFY IT
Y_grader = np.array(['tech', 'entertainment', 'tech', 'sport', 'business', 'business', 'politics', 'entertainment', 'politics', 'sport'])

# Calculating accuracy by comparing Y_grader and Y_custom
accuracy = np.sum(Y_grader==Y_custom) * 10

if accuracy >= 80:
  print("******** Success ********","Accuracy Achieved = ", accuracy,'%')
else:
  print("####### Failed #######","Accuracy Achieved = ", accuracy,'%')
  print("\nY_grader = \n\n", Y_grader)
  print("\n","*"*50)
  print("\nY_custom = \n\n", Y_custom)


(10, 4000)
******** Success ******** Accuracy Achieved =  90 %
