<a href="https://colab.research.google.com/github/sarthakkaushik/Diploma-Program-in-ML-and-AI/blob/main/TF_IDF_from_Scratch_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Implement TF-IDF from scratch**

In this assignment, you will implement TF-IDF vectorization of text from scratch using only Python and inbuilt data structures. You will then verify the correctness of the your implementation using a "grader" function/cell (provided by us) which will match your implmentation.

The grader fucntion would help you validate the correctness of your code. 

Please submit the final Colab notebook in the classroom ONLY after you have verified your code using the grader function/cell.

**(FAQ) Why bother about implementing a function to compute TF-IDF when it is already available in major libraries?**

Ans.
1. It helps you improve your coding proficiency.
2. It helps you obtain a deeper understanding of the concepts and how it works internally. Knowledge of the internals will also help you debug problems better.
3. A lot of product based startups and companies do focus on this in thier interviews to gauge your depth and clarity of understanding along with your programming skills. Hence, most top universities have implementations of some ML algorithms/concepts as mandatory assignments.

**NOTE: DO NOT change the "grader" functions or code snippets written by us.Please add your code in the suggested locations.**

Ethics Code:
1. You are welcome to read up online resources to implement the code. 
2. You can also discuss with your classmates on the implmentation over Slack.
3. But, the code you wirte and submit should be yours ONLY. Your code will be compared against other stduents' code and online code snippets to check for plagiarism. If your code is found to be plagiarised, you will be awarded zero-marks for all assignments, which have a 10% wieghtage in the final marks for this course.

In [27]:
# Corpus to be used for this assignment
import numpy as np
corpus = [
     'this is the first document mostly',
     'this document is the second document',
     'and this is the third one',
     'is this the first document here',
]


In [14]:
# Please implement this fucntion and write your code wherever asked. Do NOT change the code snippets provided by us.
def computeTFIDF (corpus):
  """Given a list of sentences as "corpus", return the TF-IDF vectors for all the 
  sentences in the corpus as a numpy 2D matrix. 
  
  Each row of the 2D matrix must correspond to one sentence 
  and each column corresponds to a word in the text corpus. 
  
  Please order the rows in the same order as the 
  sentences in the input "corpus". 
  
  Please order the words in the columns in the 
  alphabetic order when you featurize the corpus. 
  
  Ignore puncutation symbols like comma, fullstop, 
  exclamation, question-mark etc from the input corpus.
  
  For e.g, If the corpus contains sentences with these 
  9 distinct words, ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this'], 
  then the first column of the 2D matrix will correpsond to word "and", the second column will 
  correspond to column "document" and so on. 
  
  Write this function using only basic Python code, inbuilt Data Structures and  NumPy ONLY.

  Implement the code as optimally as possible using the inbuilt data structures of Python.
  """

  ##############################################################
  ####   YOUR CODE BELOW  as per the above instructions #######
  ##############################################################





DataType of Corpus- <class 'list'>
length of corpous - 4
length of corpous - ['this', 'is', 'the', 'first', 'document', 'mostly']


In [30]:
print("DataType of Corpus-",type(corpus))
print("length of corpous -",len(corpus))

#Creating list of unique words from our corpous
unique_words=[]
for sent in corpus:
  for word in sent.split(" "):
    unique_words.append(word)

###################################
# Checking intermidatory results
print("#"*200)    
print("Total Words-",unique_words) # Checking Total Words
print("legth of Total Words-",len(unique_words)) # Checking legth of Total Words
print("only Unique words-",set(unique_words)) # Checking only Unique words
print("length of Unique Words-",len(set(unique_words))) # Checking length of Unique Words
print("#"*200) 
###################################

unique_words=set(unique_words)
# print(unique_words)
#Creating numpy array of zeroes of length of unique words
corp_vect=np.zeros(len(unique_words))
print(corp_vect)

DataType of Corpus- <class 'list'>
length of corpous - 4
########################################################################################################################################################################################################
Total Words- ['this', 'is', 'the', 'first', 'document', 'mostly', 'this', 'document', 'is', 'the', 'second', 'document', 'and', 'this', 'is', 'the', 'third', 'one', 'is', 'this', 'the', 'first', 'document', 'here']
legth of Total Words- 24
only Unique words- {'the', 'first', 'third', 'document', 'this', 'is', 'here', 'mostly', 'and', 'one', 'second'}
length of Unique Words- 11
########################################################################################################################################################################################################
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Grader Cell
Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the computeTFIDF() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [4]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the computeTFIDF() is correct.
# Else, it will print "Failed"
###########################################
import numpy as np

# compute TF-IDF using the computeTFIDF() function
X_custom = computeTFIDF(corpus)

# Reference grader array - DO NOT MODIFY IT
X_grader = np.array(
    [[0, 0, 0, 0.12, 0.05, 0.23],
     [0, 0.1, 0, 0, 0.23, 0.1],
     [0.23, 0, 0, 0, 0.23, 0.23],
     [0, 0, 0, 0.12, 0.05, 0.23]]
     )

# compare X_grader and X_custom
comparison = ( X_grader == X_custom )
isEqual = comparison.all()

if isEqual:
  print("******** Success ********")
else:
  print("####### Failed #######")
  print("\nX_grader = \n\n", X_grader)
  print("\n","*"*50)
  print("\nX_custom = \n\n", X_custom)


####### Failed #######

X_grader = 

 [[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]

 **************************************************

X_custom = 

 None
